sonar.projectKey=devops-services-portal
sonar.projectName=DevOps Services Portal
sonar.projectVersion=1.0

sonar.sources=website

sonar.sourceEncoding=UTF-8

sonar.host.url=http://13.48.196.197:9000
sonar.login=sqa_bef5b3328f583e192b85004dfe29664ac059319c
